### PR TITLE
fix: check if db still exists where needed

### LINKED ISSUE #9: Do not fail when removing a database that does not exist
```
1.7022921911575806e+09	INFO	controllers.Database	Reconciling database	{"database": "redacted"}
1.7022921911753452e+09	ERROR	controllers.Database	Can't remove database and user	{"database": "redacted", "database": "redacted", "username": "redacted", "error": "Not Found: Database does not exist.", "errorVerbose": "Not Found: Database does not exist.:\n    REQUEST: GET http://redacted (0 bytes)\n    RESPONSE: 404 / Not Found (58 bytes)"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
```

### PR DESCRIPTION
**Pull request by mariusheine**
Closes #9

### CODE REVIEW

File: adapters/utils_test.go [hunk 1]
```diff
@@ -60,3 +60,13 @@ func testHelper(t *testing.T, ctx context.Context, adapter adapters.DatabaseAdap
...
 }
+
+func cleanupTestHelper(t *testing.T, ctx context.Context, adapter adapters.DatabaseAdapter) {
+	result, err := adapter.HasDatabaseUserWithAccess(ctx, "non-existing-db", "non-existing-user")
+	if err != nil {
+		t.Fatalf("Checking for existing database user failed: %s", err)
+	}
+	if result {
+		t.Fatalf("database and user existing but expecting to be non-existing")
+	}
```
Comment (anbraten) [inline adapters/utils_test.go:71]:
```suggestion
	}
	
	// TODO: test db.DeleteDatabaseUser
	// TODO: test db.DeleteDatabase
```
